defmodule ShuttleApi.Booking.Resources.GeoPoint do
    use Ash.Resource, data_layer: AshPostgres.DataLayer, extensions: [AshJsonApi.Resource]


  postgres do
    table "geo_point"
    repo ShuttleApi.Repo
  end

  actions do
    defaults [:create, :read, :update, :destroy]



  end

  attributes do
    # Add an autogenerated UUID primary key called `:id`.
    uuid_primary_key :id
    attribute :name, :string
    attribute :lat, :float
    attribute :lon, :float
    create_timestamp :inserted_at
    update_timestamp :updated_at
  end

  relationships do
    belongs_to :location, ShuttleApi.Booking.Resources.Location
  end

  json_api do
    type "geo"

    routes do
      base "/geo"

      get :read
      index :read
      post :create

    end
  end
end
