defmodule ShuttleApi.Booking.Resources.Route do
  use Ash.Resource, data_layer: AshPostgres.DataLayer

  postgres do
    table "route"
    repo(ShuttleApi.Repo)
  end

  actions do
    defaults [:create, :read, :update, :destroy]

    create :assign do
      accept []

      argument :from_id, :uuid do
        allow_nil? false
      end

      argument :to_id, :uuid do
        allow_nil? false
      end

      change manage_relationship(:from_id, :from, type: :append_and_remove)
      change manage_relationship(:to_id, :to, type: :append_and_remove)
    end
  end

  attributes do
    # Add an autogenerated UUID primary key called `:id`.
    uuid_primary_key :id
    attribute :name, :string
    create_timestamp :inserted_at
    update_timestamp :updated_at
  end

  relationships do
    belongs_to :to, ShuttleApi.Booking.Resources.Location
    belongs_to :from, ShuttleApi.Booking.Resources.Location
  end
end
