defmodule ShuttleApi.Booking.Resources.Seat do
  use Ash.Resource, data_layer: AshPostgres.DataLayer

  postgres do
    table "seat"
    repo(ShuttleApi.Repo)
  end

  actions do
    # Add the default simple actions
    defaults [:create, :read, :update, :destroy]

    create :new_st do
      accept [:label]

      argument :vehicle_id, :uuid do
        allow_nil? false
      end

      change manage_relationship(:vehicle_id, :vehicle, type: :append_and_remove)
    end

    update :assign do
      # No attributes should be accepted
      accept []

      argument :vehicle_id, :uuid do
        allow_nil? false
      end

      change manage_relationship(:vehicle_id, :vehicle, type: :append_and_remove)
    end

    attributes do
      # Add an autogenerated UUID primary key called `:id`.
      uuid_primary_key :id

      # Add a string type attribute called `:name`
      attribute :label, :string
      create_timestamp :inserted_at
      update_timestamp :updated_at

    end
  end

  relationships do
    belongs_to :vehicle, ShuttleApi.Booking.Resources.Vehicle
  end
end
