defmodule ShuttleApi.Booking.Resources.Vehicle do
  use Ash.Resource, data_layer: AshPostgres.DataLayer, extensions: [AshJsonApi.Resource]

  postgres do
    table "vehicle"
    repo(ShuttleApi.Repo)
  end

  actions do
    defaults [:create, :read, :update, :destroy]

    create :open do
      accept [:model, :capacity]
    end
  end

  attributes do
    # Add an autogenerated UUID primary key called `:id`.
    uuid_primary_key :id

    # Add a string type attribute called `:subject`
    attribute :model, :string

    attribute :capacity, :integer
    create_timestamp :inserted_at
    update_timestamp :updated_at
  end

  relationships do
    has_many :seats, ShuttleApi.Booking.Resources.Seat
  end

  json_api do
    type "vehicle"

    routes do
      base("/vehicle")

      get(:read)
      index(:read)
      post(:open)
    end
  end
end
