defmodule BusApi.Booking.Resources.Location do
  use Ash.Resource, data_layer: AshPostgres.DataLayer, extensions: [AshJsonApi.Resource]
  require Ash.Query

  postgres do
    table "location"
    repo(BusApi.Repo)
  end

  actions do
    defaults [:create, :read, :update, :destroy]

    create :new do
      accept [:name]

      argument :geo_point, :map do
        allow_nil? false
      end

      change manage_relationship(:geo_point, :geo_point, type: :create)
    end

    read :all do
      prepare build(load: [:geo_point])
    end
  end

  attributes do
    # Add an autogenerated UUID primary key called `:id`.
    uuid_primary_key :id

    # Add a string type attribute called `:subject`
    attribute :name, :string
    create_timestamp :inserted_at
    update_timestamp :updated_at
  end

  relationships do
    has_one :geo_point, BusApi.Booking.Resources.GeoPoint
  end

  json_api do
    type "location"

    includes([
      :geo_point
    ])

    routes do
      base("/locations")

      get(:read)
      index(:read)
      post(:new)
      # post :new, relationship_arguments: [:geo_point]
      #  related :geo_point, :read
      # relationship :geo_point, :read
    end
  end
end
