defmodule BusApi.Booking.Resources.Route do
  use Ash.Resource, data_layer: AshPostgres.DataLayer, extensions: [AshJsonApi.Resource]

  postgres do
    table "route"
    repo(BusApi.Repo)
  end

  actions do
    defaults [:create, :read, :update, :destroy]

    create :assign do
      accept [:name]

      argument :from_id, :uuid do
        allow_nil? false
      end

      argument :to_id, :uuid do
        allow_nil? false
      end

      change manage_relationship(:from_id, :from, type: :append_and_remove)
      change manage_relationship(:to_id, :to, type: :append_and_remove)
    end
  end

  attributes do
    # Add an autogenerated UUID primary key called `:id`.
    uuid_primary_key :id
    attribute :name, :string
    create_timestamp :inserted_at
    update_timestamp :updated_at
  end

  relationships do
    belongs_to :to, BusApi.Booking.Resources.Location
    belongs_to :from, BusApi.Booking.Resources.Location
    belongs_to :vehicle, BusApi.Booking.Resources.Vehicle
    has_many :trips, BusApi.Booking.Resources.Trip
  end

  json_api do
    type "route"

    includes(from: [:geo_point], to: [:geo_point])

    routes do
      base("/route")

      get(:read)
      index(:read)
      post(:assign)
    end
  end
end
